### ISSUE TITLE
PEX is not working

### ISSUE THREAD

**Issue by xAtomicWastex** [PEXPlugins/PermissionsEx#2450]
Hi, in /pl, PEX is red, and when I do /pex, nothing happens, and I need help fixing it. And before PEX stopped working, I tied /pex group Starter set default, but it basically says that this command is wrong and you should check the syntax or something like that. So please help! Thanks!
Here is my latest.log file.
My server is 1.8.8
http://hastebin.com/dotafujuti.vbs
By the way, this is not my server, it's my friend's server.

**Comment by starwarsfreak219** [comment]
Do you have Vault installed? If it is red that usually mean a dependency of the plugin is missing.

**Comment by xAtomicWastex** [comment]
@starwarsfreak219  Yes I do have Vault.

**Comment by starwarsfreak219** [comment]
Do you mine if I join your server and see what is going on? You can PM the IP through the Spigot, my name is the same as in here(starwarsfreak219).

**Comment by starwarsfreak219** [comment]
I think you might have had a permissions error which would cause the plugin to stop working. Do you think you could show us your permissions.yml?

**Comment by xAtomicWastex** [comment]
@starwarsfreak219  I sent you the IP on Spigot. And you want my perm.yml of PEX? From PEX?
If so, here's the screenshot: http://prntscr.com/blww49

**Comment by starwarsfreak219** [comment]
We have fixed the issue. :D

**Comment by Stormbow** [comment]
@starwarsfreak219 doesn't know what they're talking about.  When PEX is red, that means there is a problem with the config.yml or permissions.yml file, not that a dependency is missing for PEX.  (PEX has no dependencies.)

If @xAtomicWastex says this is resolved, or 3 days pass, I'll close this ticket.

**Comment by starwarsfreak219** [comment]
Yea, it wasn't a dependency, his permissions file had a error in it, I went on his server to see what the problem was first hand, but I thought PES had a dependency with vault... maybe not...

**Comment by xAtomicWastex** [comment]
@starwarsfreak219 @Stormbow  It's actually not fixed, starwars, you thought it was fixed, but I restarted the server, and it turned red again and it ain't working.

**Comment by starwarsfreak219** [comment]
I seen that, you didn't come back on so I couldn't help you fix the issue in that time. If you edited anything in your permissions.yml, then you might want to revert that for as there is an error in your permissions.yml again, please insure you didn't Tab in it for as YAML or YML files do not support Tabbing, you have to have spaces.

**Comment by Stormbow** [comment]
@xAtomicWastex -- copy your permissions.yml file (in full) to [Pastebin](http://pastebin.com) and I can tell you exactly where it went wrong.

**Comment by xAtomicWastex** [comment]
@Stormbow @starwarsfreak219 http://pastebin.com/DBfNskPj

**Comment by xAtomicWastex** [comment]
It's probably this: prefix: '&0[&eStarter&0] &f'

**Comment by xAtomicWastex** [comment]
Above default and below options

**Comment by xAtomicWastex** [comment]
And whenever I do /afk or /help, it says this: "Permissions manager is not accessable. Is the PermissionsEx plugin enabled?"

(There's probably more commands that have this error, but haven't found them yet)

**Comment by Stormbow** [comment]
Quite a few mistakes, actually.

First and foremost, if you're running a 1.9+ server, all of your groups will need an inheritance listed.  See line 19 [right here](http://pastebin.com/fScNAXfx) if the group is not going to actually be inheriting anything from other groups.  I would recommend you make your groups inherit from each lower group, as you see in the example I've linked for you in this note.

• Lines 28-32: Incorrect permission nodes.  If you are granting these permissions, add a space between the hyphen and the node.  If you are negating these permissions, you will do so like this: `- -permission.node` with 2 hyphens containing a space in between them and no space between the second hyphen and the node.

• Lines 33-36, 44-47, : Incorrect multiworld settings.  Delete all 2 of these lines and correct the indentation of the `options:` section and the `prefix:` value specified.  (See the example linked above, if you need help with setting the correct indentation.)  PEX does not allow prefixes based on the world that the use/group is currently in.

• Line 50: @starwarsfreak219  is not a permission node. :-)  LOL!  Delete this line.

• Line 57: The best permission node to give yourself as the server owner is actually `permissions.*` and not the wildcard `'*'` which gives you all of the permissions, even many that you don't want (but you don't know you don't want them, yet).

**Comment by xAtomicWastex** [comment]
@Stormbow  @starwarsfreak219 
 I removed line 50, I don't know who added that, I fixed the '*' and the space between the hyphen and node, didn't notice them :p 

But the first paragraph is what I didn't understand, I'm running a 1.8.8 Spigot server but we have the Via Version plugin, which allows 1.9 and 1.10 users to join. Yeah, basically, I didn't understand the first paragraph.

**Comment by Stormbow** [comment]
Show me your updated permissions.yml file.  (Be sure to re-read my previous post too.  I made a lot of edits and added more corrections that need to be made.)

**Comment by xAtomicWastex** [comment]
http://pastebin.com/AveuP52q

**Comment by Stormbow** [comment]
The file is short, so I'll correct the whole thing with the notes I posted above.  Give me about 5 minutes.

**Comment by xAtomicWastex** [comment]
Okay

**Comment by Stormbow** [comment]
Here ya go.  Try this file:

http://pastebin.com/EGi2JyjJ

**Comment by xAtomicWastex** [comment]
You're adding inheritance[] what will it do?

**Comment by Stormbow** [comment]
That's a 'closed set' where the group is not inheriting any permissions from any other group.

**Comment by xAtomicWastex** [comment]
So, the space in-between the [ ], I can put a group to get commands from the group that I've inherited in the Starter group?

**Comment by xAtomicWastex** [comment]
And what about the other groups, they don't have [ ], what's the difference

**Comment by Stormbow** [comment]
Nope.   Look at line 39 and 40.  That's how a group gains permissions that are listed in another group.

**Comment by xAtomicWastex** [comment]
So, if I put let's say moderator group perms in the Starter inheritence [ ], it'll take everything from mod and 'duplicate' it into Starter?

**Comment by xAtomicWastex** [comment]
Why did you inherit Starter group into Owner? 

Line 44, 45

**Comment by Stormbow** [comment]
If you delete the `[ ]` after `inheritance:` and add `- Dev` under line 6, the "Starter" group would then gain all the permissions that the "Dev" group had listed.

**Comment by Stormbow** [comment]
The Owner group had no permissions listed at all, and it needs an inheritance for PEX to work, so I made it inherit the only group that actually had permission ("Starter").

**Comment by xAtomicWastex** [comment]
Okay wait

**Comment by xAtomicWastex** [comment]
So Starter group won't get a perm from Owner, and every group has to have an inheritance for it to work?

**Comment by xAtomicWastex** [comment]
And here's the hard part... What group do I inherit into Starter....

**Comment by Stormbow** [comment]
Correct.  Starter will only have the permissions listed after line 7, and doesn't inherit any permissions from any other group.

And every group needs an inheritance listed, even if it's not inheriting anything.

**Comment by Stormbow** [comment]
Starter doesn't need anything, that's why we have line 6 as it is.  It's empty, nothing needs to be listed since it's not inheriting from other groups, but the inheritance section tag needs to be there, and we need to tell PEX that the group isn't inheriting anything (which we do with [ ] ).

**Comment by xAtomicWastex** [comment]
Oh, so I can make a group that has no perms and nothing, it just need to inherit a group, so I don't have to make perms for the 'fake' group

**Comment by xAtomicWastex** [comment]
So it doesn't have to inherit anything

**Comment by Stormbow** [comment]
Correct.

**Comment by xAtomicWastex** [comment]
Let's say
Admin group has world edit, and I don't want moderator to inherit from admin, since admin is closest to mod, can I [ ] mod

**Comment by Stormbow** [comment]
If you look at [my example](http://pastebin.com/8ZSHxauG), you'll see the basic structure of a server, using the most common names for all of the groups.  From lowest to highest, the groups are Guest > Member > Mod > Admin > Owner.  You'll notice they're also in the same order as we read down the file; Guest is at the top of the `groups:` section, Owner is at the bottom.  When we look at the bottom of the `groups:` section, at the Owner group, we see it inherits from the next group above it, Admin.  Admin inherits from the group above it (Mod), and so on, and so on, up the list.  When we get to the top, the Guest group is where all permissions originate, all of the most basic permissions on the server are granted there, so there is no inheritance, just the 'closed set' we discussed earlier.

**Comment by Stormbow** [comment]
(We don't normally go through dozens of posts to teach people how to use plugins.  That's what Google and YouTube are for.  ;-)  So you're getting a special treat here.)

**Comment by xAtomicWastex** [comment]
@Stormbow Well thank you <3

**Comment by xAtomicWastex** [comment]
Your link, line 88, you don't have permissions.* you have '*'

**Comment by Stormbow** [comment]
Correct.  That gives the Owner group absolutely every permission from every plugin on the server, and then we only negate the ones the group does not want, above it.

**Comment by Stormbow** [comment]
And, technically, because of that permissions setup, the Owner group could have an inheritance like line 19 too.

**Comment by Stormbow** [comment]
The reason I had you give `permissions.*` to yourself is so that you can have access to ALL of the PermissionsEx commands, no matter which group you are in, as you move around on your server to test things out and set things up.

**Comment by xAtomicWastex** [comment]
Just asking, how do I give negative?

"Note: OP players must be given negative permissions to negate pandorrabounty.cantcollect and pandorrabounty.immune"

**Comment by xAtomicWastex** [comment]
Look at line 29
http://pastebin.com/EGi2JyjJ
Here it's just black, but in the actual yml, the 1 is red, how do I fix this? Should I do - playervaults.amount.'1'?

**Comment by Stormbow** [comment]
`/pex group <group> add <permission>`

So: `/pex group Guest add -pandorrabounty.cantcollect` .

**Comment by xAtomicWastex** [comment]
btw idk what cantcollect does xD

**Comment by Stormbow** [comment]
The coloring of the text within the file doesn't actually matter.  That's caused by your text editor trying to be smart (by highlighting computer code programming) when it doesn't actually know what the hell you're typing.

**Comment by Stormbow** [comment]
cantcollect - not a plugin I have ever used or heard of, so you'll have to read that plugin's documentation (IF it even has any).

**Comment by xAtomicWastex** [comment]
It's not a plugin xD
It's a part of PandorraBounties

**Comment by Stormbow** [comment]
That's a Spigot plugin [found here](https://www.spigotmc.org/resources/pandorra-bounty.9042/).

**Comment by xAtomicWastex** [comment]
-_- I know, but I want to know what cantcollect does xD

**Comment by xAtomicWastex** [comment]
Wait, /pex group Guest add -pandorrabounty.cantcollect 

Why - and shouldn't there be a space if I were to add it to perm in yml?

**Comment by Stormbow** [comment]
-node.name to negate it.  It shows up as ` - -node.name` in the file after the command is issued.

**Comment by Stormbow** [comment]
I'm going to go ahead and close this ticket now, since it seems the original problem is solved and we're just doing Q&A now.  ;-)

**Comment by Stormbow** [comment]
You can still reply to this, it just won't spam other people with emails now.

**Comment by xAtomicWastex** [comment]
btw

**Comment by xAtomicWastex** [comment]
How do I check PEX group lists?

**Comment by xAtomicWastex** [comment]
Like a list of all of the groups

**Comment by Stormbow** [comment]
The easiest way?  Open the permissions.yml file and look at it.  LOL

To see them all in-game: See the [Commands List](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/75329-permissions-ex-commands-list-as-of-1-7-2/?unread).  `/pex groups list`

**Comment by xAtomicWastex** [comment]
XD
btw
About the prefixes and suffixes, if you have ever entered Mineplex, (UH DUH XD) their ranks, they're next to their names, how do I create something like that? 
(I will not be able to respond for at least an hour or so, busy, but will reply later!)

**Comment by Stormbow** [comment]
Prefix and Suffix are handled by [EssentialsXChat](http://ci.drtshock.net/job/essentialsx/) (in your case, since you're Spigot and using EssentialsX).  Somewhere in their config.yml, you decide what order everything is listed.

**Comment by xAtomicWastex** [comment]
Ahh okay

**Comment by xAtomicWastex** [comment]
But, I've looked over the Ess config, nothing about prefixes and suffixes...

**Comment by Stormbow** [comment]
You didn't look very well.  (That doesn't actually surprise me. :P )

[Prefix/Suffix Guide](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/69856-basic-prefix-suffix-tutorial/)

**Comment by xAtomicWastex** [comment]
LOL

**Comment by xAtomicWastex** [comment]
Niice! You made one yourself! Well, I have to go sleep, it's 4:23 AM, cya! 

Btw Storm, thank you for everything that you've done to help me and still helping me. <3

**Comment by Stormbow** [comment]
Yep.  Lots of good posts over at the [Official PEX Forums](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/).  If you need help again, post over there.  That's where I help people most of the time; this site is for trouble tickets that I can't solve over there and need @zml2008's attention.  (He's the actual PEX programmer.  I'm just the dude that help with easy stuff.)

**Comment by xAtomicWastex** [comment]
T-T

Your prefix/suffix tutorial is different T-T I found  change-displayname, it's true, but the lines are different, yours is 32, mine is 9...    http://hastebin.com/ratewojowe.sm
Can't find add-prefix-suffix   And the #format, there's no #  
etc.

**Comment by Stormbow** [comment]
Where did you download your Essentials?  What version is it?

That file looks extremely old.  On that assumption, I would delete that file and let Essentials create it anew.  Then check the contents of the new file?

**Comment by xAtomicWastex** [comment]
You want me to delete the file and let the .jar create a new one?


I downloaded it from here http://ci.drtshock.net/job/essentialsx/

**Comment by Stormbow** [comment]
No, delete the config.yml file and let EssentialsX create a new one.

**Comment by Stormbow** [comment]
There is a MASSIVE amount of stuff missing compared to the discontinued "Essentials" config.yml from which EssentialsX was made.

Is there an **EssentialsXChat** folder or config file somewhere?

**Comment by xAtomicWastex** [comment]
I don't see EssXChat in the Ess folder nor do I see it in the plugins section, but I see the EssXChat.jar, but not the file itself...  :laughing: 

And how do I make non-ops not able to see /pl? Because non-ops can do /pl and look, how do I make it say like, no plugins in here! or something like that?

**Comment by xAtomicWastex** [comment]
Soo, I should delete config.yml?

**Comment by Stormbow** [comment]
1. Stop your server.
2. Delete the config.yml file that's inside the Essentials and/or EssentialsX folder.
3. Start the server.  EssentialsX will make a new config.yml file.  If that file doesn't look like the example in the prefix/suffix guide, you'll need to find the people who made that plugin to find out why all the other settings are missing and how those are modified.  (I don't use Spigot on my server, so I'm not familiar with it specifically.)

As for the OP stuff...  Don't ever use OP.  OP is for servers which use no plugins at all.  Using OP on a server that does have plugins can make you think things are programmed correctly when they're actually not.

Since the /pl command is a vanilla command, you're not likely to be able to control it at all.  [Read this](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/86945-problems-with-vanilla-permissions/).  There's nothing I can do about that.  You can try negating `bukkit.command.plugins`, but don't expect it to work because it's a vanilla permission node.  You can always go look for a plugin to hide the plugins list, too.  Personally, I never had a need to hide my plugins list.

**Comment by xAtomicWastex** [comment]
Ok! It's a new config! Just like your tutorial! Thanksss!!! <3

**Comment by xAtomicWastex** [comment]
But I still don't see #2 and #3 from your tutorial..

Line 525: # Defines the balance with which new players begin. Defaults to 0.
Line 599 & 600: format: '{DISPLAYNAME} {MESSAGE}'
  #format: '&7[{GROUP}]&r {DISPLAYNAME}&7:&r {MESSAGE}'
Line 42: # When EssentialsChat.jar isn't used, force essentials to add the prefix and suffix from permission plugins to displayname.

**Comment by Stormbow** [comment]
Show me your file.

**Comment by xAtomicWastex** [comment]
http://hastebin.com/behehizatu.coffee

**Comment by Stormbow** [comment]
That link contains no content.

**Comment by xAtomicWastex** [comment]
Wait what...  The link suddenly doesn't have anything and the new config is gone, it changed back into the normal one......

**Comment by Stormbow** [comment]
Do [it](https://github.com/PEXPlugins/PermissionsEx/issues/2450#issuecomment-229462039) over again, obviously.
