### ISSUE TITLE
Can't solve my problem

### ISSUE THREAD

**Issue by goldenmasterly** [PEXPlugins/PermissionsEx#2612]
I am trying to set up pex on my server but it's not working I will put a player in a group and the can't access any commands/primision noses in that group

**Comment by Stormbow** [comment]
You've obviously setup PEX incorrectly.

Which version of PEX and Minecraft are you running?

**Comment by goldenmasterly** [comment]
Pex version 1.23.4 and Minecraft version 1.11

**Comment by Stormbow** [comment]
Copy your console/startup log and your permissions.yml file to [Pastebin](http://pastebin.com).'

Leave 2 seperate links in this thread for me to look at.

**Comment by goldenmasterly** [comment]
permisions.yml http://pastebin.com/RS28qpyi
consel http://pastebin.com/Nn0DctW6
 hopefully you can figure out my problem

**Comment by Stormbow** [comment]
It appears that your server is being bombarded by hundreds of WorldEditSelectionVisualizer errors:

`[Server] WARN Task #6 for WorldEditSelectionVisualizer v1.4.4 generated an exception`

The above error appears in your console log 25 times and I don't see anything else about your server in the log because of all that spam.  I would recommend stopping the server, removing that plugin .jar file from the server, and starting the server again to see the console log clearly.

Since you're using Minecraft 1.9 or higher, you also need an inheritance setting in every group.  See line 19 of [this example](http://pastebin.com/8ZSHxauG) to fix your "Guest" group.  This is more than likely one of the two reasons your server is not working.

And finally, the `schema-version: 1` line should be above the *users:* section.  This is the other of two reasons your server is not working.

**Comment by goldenmasterly** [comment]
fixed my permission.yml and removed world edit visualizer and now the server dosnt say pex is installed

**Comment by Stormbow** [comment]
Show me the new console log without WEV installed.

**Comment by goldenmasterly** [comment]
http://pastebin.com/GQpHQqWn

**Comment by Stormbow** [comment]
Your permissions.yml file is still showing errors in the console log.

Attach the file to your reply to this post by dragging it into the textarea where you type your reply.

**Comment by goldenmasterly** [comment]
pex now says its installed but non op don't have access to any commands
[pex.zip](https://github.com/PEXPlugins/PermissionsEx/files/670306/pex.zip)

**Comment by goldenmasterly** [comment]
server just up dated to 1.11.2

**Comment by Stormbow** [comment]
Never use OP.  OP is for vanilla servers that don't use any plugins at all.

What commands do users not have access to?

**Comment by goldenmasterly** [comment]
A bunch of essentials commands

**Comment by Stormbow** [comment]
Give them permission to do those commands then.

**Comment by Kwright02** [comment]
The issue might be the command you're using to set the group. /pet user (usr) group set (group) 
Is the command that works, and /pex user (usr) set group (group)  does t do anything

**Comment by Kwright02** [comment]
Pex not pet*

**Comment by Stormbow** [comment]
This ticket is closed.
